# site-common tasks :: Main site setup common tasks
---

- name: Generate System User/Group name
  set_fact: sysgroup={{ site_url | regex_replace('\W', '_') | lower }}
  when: site_url is defined

- name: Add System Group
  group: name={{ sysgroup }} state=present
  when: sysgroup != ''

- name: Add System User
  user: name={{ sysgroup }} group={{ sysgroup }}
  when: sysgroup != ''

