# mysql tasks :: Main MySQL setup
# http://dba.stackexchange.com/questions/31308/mysql-install-db-how-to-set-the-root-password
---
- name: Install MySQL Server
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
  - mysql-server
  - python-mysqldb
  - libmysqlclient-dev
  tags: install

- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" host="localhost" state="absent"

- name: delete empty MySQL server user for localhost
  action: mysql_user user="" state="absent"

- name: remove the MySQL test database
  action: mysql_db db=test state=absent

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: Change root user password on first run
  mysql_user: login_user=root
              login_password=''
              name=root
              password={{ mysql_root_pass }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost