---
- name: Add New Relic Repositories
  command: echo deb http://apt.newrelic.com/debian/ newrelic non-free >> /etc/apt/sources.list.d/newrelic.list
  register: added_nr_repo

- name: Add New Relic Keyserver
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present
  when: added_nr_repo|success
  register: added_nr_keyserv

- name: Install New Relic
  apt: pkg=newrelic-sysmond state=installed update_cache=true
  when: added_nr_keyserv|success
  tags: install

- name: Set New Relic License Key
  shell: nrsysmond-config --set license_key={{ newrelic_lic_key }}
  notify: Start New Relic