---
- name: Install A New Site
  hosts: all

  # remote_user: user
  become: yes
  become_method: sudo

  vars_prompt:
    #- name: sysgroup
    #  prompt: "System Group and User (same name)"
    #  private: no
    #  default: "google"
    - name: site_url
      prompt: "Website URL"
      default: google.com
      private: no
    - name: use_db
      prompt: "Set up Database?"
      default: "yes/no"
      private: no
    - name: use_wp
      prompt: "Use WordPress?"
      default: "yes/no"
      private: no
    - name: wp_email
      prompt: "WP Email Address (username will be split('@')[0] )"
      default: "user@email.com"
      private: no
    - name: wp_pass
      prompt: "WP Password"
    - name: use_mailgun
      prompt: "Use Mailgun?"
      default: "yes/no"
      private: no



  roles:
    - { role: site-common,  tags: ['site-common', 'site-wp'] }
    - { role: site-nginx,   tags: ['site-nginx'] }
    - { role: site-phpfpm,  tags: ['site-phpfpm'] }
    - { role: site-mysql,   tags: ['site-mysql'] }
    - { role: site-mailgun, tags: ['site-mailgun'] }
    - { role: site-wp,      tags: ['site-wp'] }
    - { role: debug,        tags: ['debug'] }
