---
- name: Install A New Site
  hosts: all

  # remote_user: user
  sudo: yes

  vars_prompt:
    - name: sysgroup
      prompt: "System Group"
      private: no
      default: "google"
    - name: sysuser
      prompt: "System User"
      private: no
      default: "google"
    - name: site_url
      prompt: "Website URL"
      default: google.com
      private: no
    - name: use_db
      prompt: "Set up Database?"
      default: "yes/no"
      private: no
    - name: use_wp
      prompt: "Use WordPress?"
      default: "yes/no"
      private: no
    #- name: install-plugins
    #  prompt: "Install Plugins?"
    #  default: "yes/no"
    #  private: no
    - name: wp_user
      prompt: "WP Username"
      default: "admin_google"
      private: no
    - name: wp_email
      prompt: "WP Email Address"
      default: "user@email.com"
      private: no
    - name: wp_pass
      prompt: "WP Password"



  roles:
    - { role: site-common,  tags: ['site-common'] }
    - { role: site-nginx,   tags: ['site-nginx'] }
    - { role: site-phpfpm,  tags: ['site-phpfpm'] }
    - { role: site-mysql,   tags: ['site-mysql'] }
    - { role: site-wp,      tags: ['site-wp'] }
    #- { role: wp-plugins,   tags: ['wp-plugins'] }
