# site-wp tasks :: New site WP setup
---

# Tstamp used for Redis DB number
- name: Generate Timestamp
  shell: date +%s
  register: tstamp

- name: Is WordPress downloaded?
  stat: path="{{ webroot }}/{{ site_url }}/public/index.php"
  register: wp_present

- name: WordPress Configured
  stat: path="{{ webroot }}/{{ site_url }}/public/wp-config.php"
  register: wp_configured

- name: Download WordPress
  when: use_wp == 'yes' and wp_present.stat.exists == False
  shell: wp core download --allow-root --path={{ webroot }}/{{ site_url }}/public
  register: wp_downloaded

- name: File Ready Test
  when: wp_downloaded or wp_present.stat.exists == True
  set_fact: system_ready=true

- name: Read DB User
  command: "cat {{ webroot }}/{{ site_url }}/ansible_db_user.json"
  register: db_user

- name: Read DB Pass
  command: "cat {{ webroot }}/{{ site_url }}/ansible_db_pass.json"
  register: db_pass

- name: Configure WordPress
  when: use_wp == 'yes' and system_ready and wp_configured.stat.exists == False and db_user is defined and db_pass is defined
  shell: wp core config --allow-root --path={{ webroot }}/{{ site_url }}/public --dbname={{db_user.stdout}} --dbuser={{db_user.stdout}} --dbpass={{db_pass.stdout}}

- name: Install WordPress
  when: use_wp == 'yes' and system_ready
  shell: wp core install --allow-root --path={{ webroot }}/{{ site_url }}/public --url=http://{{site_url}} --title='{{site_url}}' --admin_user={{wp_user}} --admin_email={{wp_email}} --admin_password={{wp_pass}}

- name: Install Plugins
  when: use_wp == 'yes' and system_ready
  shell: wp plugin install {{ item }} --allow-root --path={{ webroot }}/{{ site_url }}/public && wp plugin activate {{item}} --allow-root --path={{ webroot }}/{{ site_url }}/public
  with_items:
  - nginx-helper
  - redis-cache
  - wpmandrill

- name: Update Permissions
  when: use_wp == 'yes'
  command: chown -R {{sysuser}}:{{sysgroup}} {{ webroot }}/{{ site_url }}/public

- name: Add WP Config Defines
  when: use_wp == 'yes' and system_ready
  lineinfile: dest="{{ webroot }}/{{ site_url }}/public/wp-config.php"
    regexp="\<\?php"
    insertafter="^<?php"
    line="<?php define('RT_WP_NGINX_HELPER_CACHE_PATH', '{{ webroot }}/{{ site_url }}/cache/'); define('DISABLE_WP_CRON', true); define('WP_REDIS_DATABASE', {{tstamp.stdout}}); define('WP_REDIS_PASSWORD', '{{redis_pass}}');"




